version: "3.8"

services:
  broker:
    container_name: "broker-server"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
  api:
    container_name: api-server
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4001"
    volumes:
      - "./server/:/server"
    environment:
      # BROKER_HOST: broker
      # BROKER_PORT: 5672
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - broker
